name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4.1.1

      - name: Setup biome
        uses: biomejs/setup-biome@v2.1.0
        with:
          version: latest

      - name: Run biome
        run: biome ci ./src

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4.1.1

      - name: Install pnpm
        uses: pnpm/action-setup@v3

      - name: Install node
        uses: actions/setup-node@v4.0.2
        with:
          node-version: lts/*
          cache: pnpm # Package manager should be pre-installed

      - name: Clean install
        run: pnpm i --frozen-lockfile

      - name: Typecheck
        run: pnpm typecheck

  # e2e:
  #   timeout-minutes: 30
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout branch
  #       uses: actions/checkout@v4.1.1

  #     - name: Install pnpm
  #       uses: pnpm/action-setup@v3

  #     - name: Install node
  #       uses: actions/setup-node@v4.0.2
  #       with:
  #         node-version: 18

  #     - name: Clean install
  #       run: pnpm i --frozen-lockfile

  #     - name: Install playwright browsers
  #       # since we are installing dependencies beforehand, we can `exec` the binaries directly, instead of `dlx`
  #       run: pnpm test:install

  #     - name: Run playwright tests
  #       run: pnpm test

  #     - name: Save playwright report as artifact
  #       uses: actions/upload-artifact@v4.3.1
  #       if: always()
  #       with:
  #         name: playwright-report
  #         path: playwright-report/
  #         retention-days: 30

  # e2e:
  #   runs-on: ubuntu-latest
  #   container:
  #     image: mcr.microsoft.com/playwright:v1.42.0-focal
  #   steps:
  #     - name: Checkout branch
  #       uses: actions/checkout@v4.1.1

  #     - name: Install pnpm
  #       uses: pnpm/action-setup@v3

  #     - name: Install node
  #       uses: actions/setup-node@v4.0.2
  #       with:
  #         node-version: lts/*

  #     - name: Clean install
  #       run: pnpm i --frozen-lockfile

  #     - name: Run playwright tests
  #       run: pnpm test
  #       env:
  #         HOME: /root
