name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4.1.1

      - name: Setup biome
        uses: biomejs/setup-biome@v2.1.0
        with:
          version: latest

      - name: Run biome
        run: biome ci ./src

  typecheck-and-e2e:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4.1.1

      - name: Install pnpm
        uses: pnpm/action-setup@v3

      - name: Install node
        uses: actions/setup-node@v4.0.2
        with:
          node-version: lts/*
          cache: pnpm # Package manager should be pre-installed

      - name: Setup ni
        run: npm i -g @antfu/ni

      - name: Clean install
        run: nci

      - name: Typecheck
        run: nr typecheck

      - name: Install playwright browsers
        run: nlx playwright install --with-deps

      - name: Run playwright tests
        run: nr test

      - name: Save playwright report as artifact
        uses: actions/upload-artifact@v4.3.1
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
